name: Lint and test

on: [push, pull_request]

jobs:
  default-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 12

    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn build-all